### PR TITLE
Assets from Gems Section

### PR DESCRIPTION
**Pull request by hummusonrails**
Adding a guide for Webpacker is so important, and the work here is fantastic! 💙 

I've gone ahead and introduced a Troubleshooting section, which Noel had prepared an area for in his [first take on this](https://github.com/noelrappin/rails_javascript_documention_drafts/blob/master/webpacker_guide.md#troubleshooting-common-problems). In the section I added one topic on addressing assets from Gems with Webpacker, and laid out the most common approaches currently that I've discovered in my research. This was an area we struggled with quite a bit at work as we have begun finishing the migration of our assets to Webpacker and would love to spare others in the future some time by adding a bit on it here.

Thanks for considering!

Specifically, this PR: 

* Adds a troubleshooting top-level section
* Adds a guide to the current options for addressing assets from Gems with Webpacker

EDIT: After the first revision, I've gone ahead and moved the topic to its own section and removed the proposed Troubleshooting section.

### CODE REVIEW

**Comment by rossta** [comment]
@bencgreenberg Thanks for this PR! A few comments:

* I'd say we can make this its own section separate from Troubleshooting. What do you think?
* Though it may be the case that there is currently no agreed-upon best practice—to elablorate on my tweet from earlier—I'm inclined to start by putting forth a single recommended best practice as part of the guide, which, in my opinion, would be the first of the options you've presented (separate NPM packages). If you agree, could you reword and point to some examples? (Webpacker itself comes to mind)

**Comment by hummusonrails** [comment]
> * I'd say we can make this its own section separate from Troubleshooting. What do you think?

Sure, that sounds like a good idea!

> * Though it may be the case that there is currently no agreed-upon best practice—to elablorate on my tweet from earlier—I'm inclined to start by putting forth a single recommended best practice as part of the guide, which, in my opinion, would be the first of the options you've presented (separate NPM packages). If you agree, could you reword and point to some examples? (Webpacker itself comes to mind)

While I do think that ought to be the recommended approach, it doesn't, however, do much for those who are not the gem owner. I don't think I'd want to recommend that people take the assets from a gem they don't maintain and on their own publish them as an NPM package. I also wouldn't want to tell people to start banging down the door of every gem maintainer and asking them to publish NPM packages, either. That might not get a lot of appreciation from all the hard working maintainers out there! That's why I'm inclined to include at least one other option as well.

**Comment by hummusonrails** [comment]
Good morning @rossta, anything I can do to help move this forward? 🙏🏻

**Comment by hummusonrails** [comment]
Hi @rossta, it seems your PR was merged into Rails a little while ago, so I'm going to go ahead and close this PR in your branch. Have a great day.

**Pull request closed without merging**
